#ifndef _INTR_H_INCLUDED_
#define _INTR_H_INCLUDED_

#define NUMBER_OF_INTERRUPT_VECTORS 64

/* TODO:トラップ命令割込実装 */
#define SOFTVEC_TYPE_SOFTERR 0
#define SOFTVEC_TYPE_SYSCALL 1

#define RXI1_VECTOR_SUBSCRIPT 57

#endif
